name: Docker Image CI for GHCR 
on: 
push: 
branches: [ main ] 
pull_request: 
branches: [ main ]
jobs: 
build: 
runs-on: ubuntu-latest
steps: 
- uses: actions/checkout@v3
- name: Build & Push the Image
run: 
echo "${{ secrets.GH_PAT}}" |  docker login --username oftharsh --password-stdin
docker image build -t ghcr.io/oftharsh/docker-container-ghcr:latest 
 docker pull ghcr.io/oftharsh/docker-container-ghcr:latest
