name: Docker Image CI for GHCR 

on:
   push 

jobs:
 build_and _publish 
  runs-on: ubuntu-latest 
  steps:
  - uses: actions/checkpout@v3
  - name: Build and push image 
    run:
      docker login --username oftharsh --password ${{ secrets.GH_PAT }} ghcr.io
      docker build .io --tag ghcr.io/oftharsh/docker-container-ghcr:latest
      docker push ghcr.io/oftharsh/docker-container-ghcr:latest
